### ISSUE TITLE
Issues with 2014 data

### ISSUE THREAD

**Issue by mike-joyce** [stevevance/divvy-munging#2]
I was looking at the 2014 data, and was surprised to see that while Q1/Q2 gender is "Male", "Female", or "", in the 3 Q3/Q4 .csv files gender is "0", "1", or "2". 
**Any idea what do "0", "1", and "2" correspond to?**

Also, I noticed that a couple of rides (<200) where usertype = "Customer" (rather than "Subscriber") and gender = "Male" or "Female".
**What does it mean for customer (i.e. not subscriber) gender to be known?**

Finally,
**What does usertype  = "Dependent" mean?**

**Comment by Chicago-Dave** [comment]
Hello:

I recently returned to the data for a grad school visualization project, discovered the same discrepancy, and determined (by inference) that 1 is male and 2 is female. That was based on the aggregate ratio between the two being consistent with the male to female users in 2103 and Q1Q2.

There was no notation in the realm files. I think my assumption is reasonably sound. It would be unlikely for the gender ratio to suddenly flip.

David Thomas

**Comment by mike-joyce** [comment]
Divvy has updated the dataset - the 2014 Q3 and Q4 results now have "Male", "Female", and "".

**Comment by Chicago-Dave** [comment]
Thanks - by any chance did you find a third usertype called "Dependent"? I found 61 records, all male, all born in 1979. Great similarity to start & end points.

**Comment by mike-joyce** [comment]
Yes! I did see that, and got a response from Elliot Greenberger @ Divvy:

"FYI, "dependent" would refer to someone under 16 whose parent purchased them a membership."

Still waiting to hear back about what it means for customer gender to be known.

**Comment by naltmann** [comment]
What file did you see "Dependent" in, or is this something they've also
removed

**Comment by mike-joyce** [comment]
It was removed in the most recent version of the dataset.

**Comment by Chicago-Dave** [comment]
Do you think the "Dependent" addition was an accident? Could there really only be one individual case of a 'Dependent' class? This has implications regarding what can really be deduced from the 'birthyear' attribute. Any age group demographic claims must be made with a huge asterisk if 'Subscriber' and 'birthyear' really only indicate for certain the fee payer, not necessarily the renter/rider. I'd always assumed the 'Subscriber' key fob could be shared by multiple people, but the probability of adult owner/under 18 user was relatively small.

**Comment by mike-joyce** [comment]
I believe it's intentional. You can join Divvy at 16 if your parents give permission - see the bottom of https://www.divvybikes.com/signup/pedal?commit=BECOME+A+%E2%80%9CPEDAL%E2%80%9D+MEMBER+NOW.

This afternoon I'll check the original version of the dataset and count "Dependent" rides there were, and check the birthyears.

**Comment by stevevance** [comment]
@PredictiveAnalytics The Subscriber's key fob can definitely be used by more than one person but the terms and conditions only allow the subscriber to use the key fob. 

We – the Divvy data users – have essentially assumed that the Gender and Age data is 100% accurate. Because we have no other data to sample and because it's just easy and the consequences of making a mistake in this assumption are not grave.
